### ISSUE TITLE
Packages...

### ISSUE THREAD

**Issue by unsigned-long-long-int** [Its-Jakey/Linux-On-Scratch#1]
Where can I find packages and how can I install them?

**Comment by NexusSfan** [comment]
Right now there isn't a package manager, at least I think so.

**Comment by Its-Jakey** [comment]
No package manager currently, if you want more packages you have to rebuild the kernel using the buildroot included in [cnlohr's mini-rv32ima](https://github.com/cnlohr/mini-rv32ima/tree/master)

**Comment by ghost** [comment]
Yeah, but how do I attach the compiled Kernel to the project, and which file do I attach?

**Comment by ghost** [comment]
And also, how do I attach files so I can load and run custom code?

**Comment by Its-Jakey** [comment]
> And also, how do I attach files so I can load and run custom code?

I don't have all the stuff with the toolchain setup yet, so you can't compile your own code to run on the baremetal system

**Comment by Its-Jakey** [comment]
> And also, how do I attach files so I can load and run custom code?

Convert each byte into the file into ascii, and put each byte on a new line. Then load it into the rom list in the scratch project
